import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componenets/global/Navbar";
import Footer from "@/componenets/global/Footer";
import CapabilitiesStrip from "@/componenets/CapabilitiesStrip";
import CustomCursor from "@/componenets/global/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className="bg-white text-black">
        <CustomCursor />
       {/* Fixed header: stripe + navbar */}
      <div className="fixed top-0 left-0 w-full z-50">
        <CapabilitiesStrip />
        <Navbar />
      </div>
        <main className="pt-34">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
